# Nonprofit Social Networking Platform: Allowing Users and Organizations to Collaborate.
# Copyright (C) 2023  ASCENDynamics NFP

# This file is part of Nonprofit Social Networking Platform.

# Nonprofit Social Networking Platform is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Nonprofit Social Networking Platform is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with Nonprofit Social Networking Platform.  If not, see <https://www.gnu.org/licenses/>.
name: Deploy to PROD Firebase

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v4

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Cache Node.js modules
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            functions/node_modules
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4. Install project dependencies
      - name: Install dependencies
        run: npm ci

      # 5. Set Firebase environment variables
      - name: Set environment variables
        run: |
          echo "CI=true" >> $GITHUB_ENV
          echo "NODE_ENV=production" >> $GITHUB_ENV
          echo "FIREBASE_API_KEY=${{ secrets.PROD_FIREBASE_API_KEY }}" >> $GITHUB_ENV
          echo "FIREBASE_AUTH_DOMAIN=${{ secrets.PROD_FIREBASE_AUTH_DOMAIN }}" >> $GITHUB_ENV
          echo "FIREBASE_PROJECT_ID=${{ secrets.PROD_FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_STORAGE_BUCKET=${{ secrets.PROD_FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV
          echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.PROD_FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_APP_ID=${{ secrets.PROD_FIREBASE_APP_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_MEASUREMENT_ID=${{ secrets.PROD_FIREBASE_MEASUREMENT_ID }}" >> $GITHUB_ENV

      # 6. Generate environment file
      - name: Generate environment file
        run: node generate-env.js

      # 7. Build the project for production
      - name: Build
        run: npm run build:prod

      # 8. Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 9. Install and Build Firebase Functions
      - name: Install and Build Firebase Functions
        run: |
          cd functions
          npm ci
          npm run build # Ensure this script exists in functions/package.json

      # 10. Authenticate to Firebase
      - name: Authenticate to Firebase
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.PROD_GOOGLE_APPLICATION_CREDENTIALS }}

      # 11. Deploy to Firebase Hosting and Functions
      - name: Deploy to Firebase
        run: firebase deploy --force --project ${{ secrets.PROD_FIREBASE_PROJECT_ID }} --only hosting,functions
