# Nonprofit Social Networking Platform: Allowing Users and Organizations to Collaborate.
# Copyright (C) 2023  ASCENDynamics NFP

# This file is part of Nonprofit Social Networking Platform.

# Nonprofit Social Networking Platform is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Nonprofit Social Networking Platform is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with Nonprofit Social Networking Platform.  If not, see <https://www.gnu.org/licenses/>.
name: Build and Deploy to Firebase on Merge (Development)

on:
  push:
    branches:
      - main  # Trigger workflow on push events to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - name: Install Dependencies
        run: |
          npm ci
          npm ci --prefix functions

      # Set Environment Variables
      - name: Set Environment Variables
        run: |
          echo "CI=true" >> $GITHUB_ENV
          echo "NODE_ENV=development" >> $GITHUB_ENV
          echo "FIREBASE_API_KEY=${{ secrets.DEV_FIREBASE_API_KEY }}" >> $GITHUB_ENV
          echo "FIREBASE_AUTH_DOMAIN=${{ secrets.DEV_FIREBASE_AUTH_DOMAIN }}" >> $GITHUB_ENV
          echo "FIREBASE_DATABASE_URL=${{ secrets.DEV_FIREBASE_DATABASE_URL }}" >> $GITHUB_ENV
          echo "FIREBASE_PROJECT_ID=${{ secrets.DEV_FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_STORAGE_BUCKET=${{ secrets.DEV_FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV
          echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.DEV_FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_APP_ID=${{ secrets.DEV_FIREBASE_APP_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_MEASUREMENT_ID=${{ secrets.DEV_FIREBASE_MEASUREMENT_ID }}" >> $GITHUB_ENV
          
      # Generate environment file
      - name: Generate Environment File
        run: node generate-env.js

      # Build the project (Development)
      - name: Build Project
        run: npm run build:dev

      # Build Firebase Functions
      - name: Build Firebase Functions
        run: npm run build --prefix functions

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ASCENDCOOPPLATFORM_DEV }}'

      # Set up Firebase Function Secrets
      - name: Set up Firebase Function Secrets
        run: |
          # Check if secrets exist, if not set them
          firebase functions:secrets:access GOOGLE_API_KEY --project ${{ secrets.DEV_FIREBASE_PROJECT_ID }} 2>/dev/null || \
          echo "${{ secrets.DEV_GOOGLE_API_KEY }}" | firebase functions:secrets:set GOOGLE_API_KEY --project ${{ secrets.DEV_FIREBASE_PROJECT_ID }} --force
          
          firebase functions:secrets:access GMAIL_EMAIL --project ${{ secrets.DEV_FIREBASE_PROJECT_ID }} 2>/dev/null || \
          echo "${{ secrets.DEV_GMAIL_EMAIL }}" | firebase functions:secrets:set GMAIL_EMAIL --project ${{ secrets.DEV_FIREBASE_PROJECT_ID }} --force
          
          firebase functions:secrets:access GMAIL_PASSWORD --project ${{ secrets.DEV_FIREBASE_PROJECT_ID }} 2>/dev/null || \
          echo "${{ secrets.DEV_GMAIL_PASSWORD }}" | firebase functions:secrets:set GMAIL_PASSWORD --project ${{ secrets.DEV_FIREBASE_PROJECT_ID }} --force
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ASCENDCOOPPLATFORM_DEV }}

      # Deploy to Firebase
      - name: Deploy to Firebase
        run: firebase deploy --project ${{ secrets.DEV_FIREBASE_PROJECT_ID }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ASCENDCOOPPLATFORM_DEV }}
